import NavigationList from '../NavigationList/NavigationList.vue';

/**
 * Get navigation item - a hyperlink, a router link, or a simple value.
 * Return only `name` in case both `route` and `element` are not defined.
 * Return <router-link to=`meta.location`>`name`</router-link> if `route` is defined.
 * Return <a href=`meta.location`>`name`</a> when `element` is defined.
 */
function getNavItem(createElement, item) {

  if (item.route === undefined && item.element === undefined) {
    return item.name;
  }

  let elementName;
  let attrs;
  let props;
  let classes;

  if (item.element !== undefined) {
    elementName = 'a';
    attrs = {
      href: item.meta.path,
    };
    props = {};
    classes = [];
  }

  // user shouldn't define both `route` and `element` but in case he does,
  // `element` will be overridden by `route` which has a higher priority
  if (item.route !== undefined) {
    elementName = 'router-link';
    attrs = {};
    props = {
      to: item.meta.path,
    };
    classes = ['router-link']; // it is useful to be able to recognize if the <a> element was
                               // generated by the vue-router or if it is just a simple <a>
                               // (so we can style router links in a different way)
  }

  return createElement(elementName, {
    attrs,
    props,
    'class': classes,
  }, [
    item.name,
  ]);
}

/**
 * Recursive function.
 * Insert metadata containing the navigation path and its type to each item.
 **/
function insertMetadataToItems(items) {
  // dummy
  items.forEach(item => {
    item.meta = {
      path: '#',
      pathType: undefined,
    };
    if (item.hasOwnProperty('children')) {
      item.children = insertMetadataToItems(item.children);
    }
  });
  return items;
}

/**
 * Recursive function.
 * One call generates one level of the tree.
 */
function generateLevel(createElement, items, level, defaultOpenLevel) {
  const children = [];

  items.forEach(item => {
    const navItem = getNavItem(createElement, item);

    if (item.hasOwnProperty('children')) {
      children.push(
        createElement(NavigationList, {
          props: {
            level,
            defaultOpenLevel,
          },
        }, [
          navItem,
          ...generateLevel(createElement,
                           item.children,
                           level + 1,
                           defaultOpenLevel),
        ])
      );
    } else {
      children.push(createElement('li', [
        navItem,
      ]));
    }
  });

  return children;
}

export default {
  insertMetadataToItems,
  generateLevel,
};
