name: Build Vue

on:
  push:
    branches: [ "master" ]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: J3-Tech/VuePagesAction@0.0.4
      with:
        cname: vue-tree-navigation.j3-tech.com
        username: 'J3-Tech'
        reponame: 'Vue-Tree-Navigation'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
